"""empty message

Revision ID: 653caf7215c8
Revises: 85bd47ba6bc9
Create Date: 2023-04-21 11:43:18.554092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653caf7215c8'
down_revision = '85bd47ba6bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
