"""empty message

Revision ID: b7673ed3caee
Revises: f9fd1d162748
Create Date: 2023-04-27 00:59:56.454416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7673ed3caee'
down_revision = 'f9fd1d162748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('likes_count')
        batch_op.drop_column('like')

    # ### end Alembic commands ###
